#!/usr/bin/env python

import zmq
from time import sleep

"""
Tiny sample of a listener that only outputs MSGCMDOUTPUT messages
from any minion.
"""

context = zmq.Context()
socket = context.socket(zmq.PULL)
socket.bind ("tcp://*:10081")
while True:
    s = socket.recv_multipart()
    if len(s) > 3 and s[2] == 'MSGCMDOUTPUT':
        print s[3]

sleep(1)

